### ISSUE TITLE
SIG Bid

### ISSUE THREAD

**Issue by MartinHinz** [sslarch/sslarch.github.io#23]
Dear all, especially @nevrome and @SCSchmidt,

Thank you, Clemens, for starting the Bid text. I have partly changed text parts and added the whole statement of purpose. Now, you might suggest shortenings, corrections and changes. Please, do so! Find the current version at 

https://github.com/sslarch/sslarch.github.io/blob/master/caa_proposal.md

Cheers,

Martin

**Comment by zackbatist** [comment]
Hi! Although I'm not a signatory I submitted a PR with some revisions to consider implementing. Please see the PR (https://github.com/sslarch/sslarch.github.io/pull/24) for a summary of my thoughts.

**Comment by nevrome** [comment]
Although I agree with many of the changes and simplifications you made, @zackbatist, I don't see the point of this major rewrite. I also dislike the fact that the Statement of Purpose on the website deviates from the version we submit to CAA. If we apply these changes here, we should IMHO apply them there first.

I suggest to keep the the original text and introduce some of your suggestions. A better, merged version of the first paragraph could for example be: 

> The purpose of the CAA Special Interest Group Scientific Scripting Languages in Archaeology is to promote the use of scripting languages in archaeology and to help foster the growing community of archaeologists who apply them to better align the practice of archaeology with the goals of archaeological science. Scientists use scripting languages to write computer programs (scripts) that automate the execution of various kinds of tasks, and to process and visualize information in ways that are amenable to the principles of open research.

It's also a good idea to replace Observable in the language list with Javascript and I like your replacement of line 19.

Concerning your notes and questions:

***

> ==[ZB note: the links between inclusivity, reproducibility and open source software needs to be explained and argued for more thoroughly in order to justify the inclusion of the latter two in the same breath as a paragraph about the first.]==

IMHO we don't need any justification for more inclusivity. It's a completely independent value. The connection between reproducibility and open source could be stressed with an addition to line 13:

> To be as inclusive as possible and also for the sake of reproducibility we strongly prefer open-source over proprietary software. Open source software can be freely accessed, modified and copied by everyone without exception.

***

> - Promote the use of scripting languages to replace widely-used black-box software with transparent and reproducible code written in open source languages ==[ZB note: why though?]==

I would argue that this question is well answered in the preceding paragraphs.

***

> - promote the publication of archaeological research data ==[why though? the link with scripting needs to be demonstrated]==

Again: If we keep the original paragraphs, then this is pretty clear in my opinion. For example in line 34: 

> The use of scripting languages for research allows the user to document every necessary step in a research pipeline. The resulting script can be used to reproduce the data analysis by other researchers, given that also the input datasets are provided and – if necessary – the required software environment can be emulated

and line 42:

> Reproducible research ideally also documents the science production process with all inductive and deductive steps of hypothesis building.

***

I don't want to dismiss your points, @zackbatist. I even see some strong arguments for the increased elegance and simplicity of your text and I would not be surprised if @MartinHinz, @SCSchmidt or others prefer your updated version. I personally prefer the comprehensiveness of the original version though, which already went through stepwise improvements in multiple iterations.

**Comment by zackbatist** [comment]
I'm sorry, I didn't mean to step on your toes. You're right, I was looking at this document exclusively and was not considering the other complementary documentation on the website. That being said, I'm glad that some of these suggestions are being considered.

I just want to clarify a few things regarding the notes you highlighted. First regarding my comment on inclusivity, reproducibility and open source software: the way that it is currently phrased seems to suggest that implementation of reproducible methods and open source software are major factors that promote inclusivity, but it is unclear whether or how that is true. In retrospect, I don't think this is necessarily the right venue to argue about that, but I just want to make clear what I meant.

Regarding the second note, I don't feel it is clear what widely used black box software is and why it's necessarily bad. My aim isn't to take a stance, just to highlight that I believe more specificity is needed. As a potential alternative, maybe consider this:
> promote the replacement of proprietary and opaque programs with open source and transparent software based on scripting languages, which encourage the advancement of open and reproducible research practices

Regarding the third note, I see bullet lists kind of like summaries, and I think that they should typically capture as much information as needed without having to refer elsewhere in the text.
This alternative phrase might be more suitable includes aspects of the other relevant lines you mentioned:
> promote the publication of archaeological research data so that they may be used by others, and to facilitate reproducible research practices overall

These are just some suggestions based on my own perspective. I probably should have introduced my comments with where I'm coming from, in retrospect. Feel free to use them (or not use them) however you see fit.

**Comment by nevrome** [comment]
@zackbatist Don't worry: This is an important process of negotiation to find a good consensus. :+1: 

I agree with all of the changes you suggest here and I understand now where the initial wording fell short. 

The next step would probably be to craft a modified version of the text that includes these changes. I can offer to do so, but maybe it's better to wait for the opinions of the other stakeholders after the Christmas/New Year break.

**Comment by zackbatist** [comment]
Sounds good. I just updated the PR to remove the notes and replace them with these tentative phrases. I will take a closer look in the new year.

**Comment by SCSchmidt** [comment]
Hi, sorry for joining in so late. 
Thank you, @nevrome for your draft and @zackbatist for your helpful discussion and comments!

I agree the statement of purpose should be consistent with the version on the website, which has been agreed on by all the others before, so I'd prefer to keep that. 

In line 30 I see why @zackbatist deleted the explanation of the different scripting languages. It is not really relevant to our case that they differ. We decided and that's nicely explained in the beginning that we would be open to different languages, not just R. We show a few examples, that's fine and doesn't need an explanation. Maybe we could say something along the lines: 

> examples include, but are not limited to

 to make sure we are not excluding some language.  

I personally find @nevrome 's explanation of reproducibility more easy to understand, though I believe the sentence 

> Code should be equally important as publications. That also means that code generally should be subject to a scientific reviewing process. 

is a bullet point of its own and may be enhanced with the statement:

> It is therefore one long-term aim of this SIG to offer guidelines how code publication and - review can be fruitfully implemented into research and publication processes (see Objectives). 

I also wouldn't make a header for Version Control but embed it in the list. 

I agree with @zackbatist 's lines 42, 48, 50, but personally don't feel the other changes to make things clearer. 

Admittedly, Clemens and I may have had a similar "education" on reproducibility, therefore we might think along similar lines, which might not be so clear to others.

Cheers! :-)

**Comment by MartinHinz** [comment]
Based on the pull request of @zackbatist, which I will now accept, the discussion and the suggested changes of @SCSchmidt, I will draft a 'consensus' version. Tom has just rushed me to finally submit the bid, so I hope we can come up with a version that satisfies everyone involved. It' going out on the repo right after...

**Comment by MartinHinz** [comment]
Would you, @SCSchmidt @nevrome @zackbatist be so kind as to review the current document **(7825ed200194321a694fbdc28cd94008aed1fe32)** and if you agree, the next steps would be
[ ] align the website statement of purpose with the bid one
[ ] distribute a version via the email list and get support from other members for the necessary 'List of Potential Members'
[ ] send this to CAA

**Comment by MartinHinz** [comment]
Handed in to CAA

**Comment by joeroe** [comment]
Our bid was accepted at the 2020 Virtual Annual General Meeting.
