### ISSUE TITLE
Handing in the bid do CAA

### ISSUE THREAD

**Issue by MartinHinz** [sslarch/sslarch.github.io#25]
What we need for that:

- [x] A title
- [x] A short description of the SIG topic demonstrating it is in the remit of CAA
- [x] A short description of planned activities demonstrating it is in line with the aims of CAA
- [x] A list of coordinators (at least one or more need to be current CAA members)
- [x] A list of potential future members who have expressed an interest (optional)

'This can all be very short, a total of 1-3 pages is definitely enough.' - Tom Brughmans

So for the remaining two points, we need the approval of the potential members of SIG (see #23). I will prepare a draft letter to inform the members, get their agreement, and make a proposal for coordinators. At the moment, the latter boils down to Sophie, Clemens and me, but we (and other potential candidates) should stand for election in a democratic process directly after the official establishment.

**Comment by MartinHinz** [comment]
Would you, @SCSchmidt @nevrome be so kind as to review the letter to the mailing list?

**Comment by SCSchmidt** [comment]
I've amended a few things, (hopefully) improving the flow of the writing.
I hope this meets your approval. :-)

**Comment by MartinHinz** [comment]
Thumbs up. Thank you!

**Comment by zackbatist** [comment]
Everything looks good to me!
Not sure if it's relevant, but I'm no longer a dues-paying member of the CAA (I can't justify the costs, and I won't be able to attend the conference this year). I would still be glad to be listed as a potential member, letter-signer, etc, just not sure whether the CAA has a 'members only' policy for these sorts of things.

**Comment by SCSchmidt** [comment]
Thanks for your work, @MartinHinz ! 

@zackbatist , I believe the coordinator needs to be a member of the CAA, but not the letter-signer. We discussed this at the meeting in Krakow, and I think the end of the discussion was, that not everyone needs to be a member of CAA to be a member of the SIG.

**Comment by nevrome** [comment]
I like everything. Good job! Go ahead!

One small thing: Shouldn't 

> A script is a computer program that automates the execution of various kinds of tasks, and are typically used by scientists ...

be for example

> Scripts are computer programs that automate the execution of various kinds of tasks, and are typically used by scientists ...

in the proposal?

**Comment by MartinHinz** [comment]
Very well. Thank you so much!

**Comment by MartinHinz** [comment]
Started a csv to list all supporting individuals at [supporters.csv](../blob/master/supporters.csv)

**Comment by MartinHinz** [comment]
We now have 16 supporters, and I don't think there will be many more in the very near future. So I would now send the bid to the CAA with the list. Please confirm it, @SCSchmidt @nevrome @zackbatist, and maybe also a note about what else we have to consider!

**Comment by keltoskytoi** [comment]
Hi, I´d love to be added to the suppers if it is still possible!

**Comment by MartinHinz** [comment]
And done!

**Comment by nevrome** [comment]
Do it, Martin!

**Comment by keltoskytoi** [comment]
Thank you guys!

**Comment by SCSchmidt** [comment]
Go for it, @MartinHinz and thank you! :-) :+1:

**Comment by zackbatist** [comment]
Looks good!

**Comment by MartinHinz** [comment]
It is up and away!
