### ISSUE TITLE
Resolve accessibility issues on the website

### ISSUE THREAD

**Issue by zackbatist** [sslarch/sslarch.github.io#37]
Someone on twitter [raised concerns](https://twitter.com/archaeometer/status/1346731960970964992) about accessibility issues pertaining to our website. Specific problems highlighted in the tweet include:
- insufficient contrast of text and background
- use of typewriter font
- use of full justification

He also provided a link to an automated service that checks for accessibility issues: https://wave.webaim.org/report#/https://sslarch.github.io/statement.html

Creating this issue to track progress on resolving this.

**Comment by joeroe** [comment]
The low contrast and justification issues come up in the link, but monospace fonts being bad for accessibility is completely new to me and I can't find anything about it. No mention here: https://webaim.org/techniques/fonts/. Can anyone shed any light?

**Comment by joeroe** [comment]
See also [Google Lighthouse report](https://googlechrome.github.io/lighthouse/viewer/?gist=28a3dc409cc68b7e7a1d748adfb7781b).

**Comment by MartinHinz** [comment]
Thank ou, Joe, I would suggest we concentrate on the issues that the lighthouse report is bringing up. And that is mainly contrast.

**Comment by MartinHinz** [comment]
By the way, thank you, too, to bring the lighthouse reports to my attention. I just checked Joes reworking of the site, related to #9, since I like the still geeky look and feel of it, I could imagine it would work just fine for us. An the [report](https://googlechrome.github.io/lighthouse/viewer/?gist=364dc40e57e75adec329ac3c43b687cb) is just fine!

**Comment by joeroe** [comment]
For the record, the latest report: https://googlechrome.github.io/lighthouse/viewer/?gist=aed2bc37a0f423b8a9c0d2abf8732290

**Comment by joeroe** [comment]
I don't think this is an issue any more. The Lighthouse report for accessibility remains very good.
