### ISSUE TITLE
Get the SIG listed on the CAA website

### ISSUE THREAD

**Issue by joeroe** [sslarch/sslarch.github.io#39]
I keep forgetting to bring this up in the meetings, so I'll do it here. I noticed we're still not listed on the [CAA's special interest groups page](https://caa-international.org/special-interest-groups/), which would be good for visibility. Is there someone we can bug to get the page updated?

Unless we're "Computer Programs for Archaeologists"? In which case we should maybe ask for a name correction and link to the website.

**Comment by MartinHinz** [comment]
Hej Joe, thanks for pointing this out. I wanted to have this sorted out and raised with the CAA for a long time, but also kept forgetting. It will be taken care of promptly!

**Comment by MartinHinz** [comment]
Mail is out, looking forward to the reply...

**Comment by MartinHinz** [comment]
Mail from Jeffrey Glocer:

Martin,

My apologies.  Lisa and I have been meaning to complete our update of the website, but CAA 2021 planning (and the switch to a virtual conference) has taken our time.  I will see what I can do about this ASAP.  

Thanks for bringing it to my attention.

Best,

Jeffrey

**Comment by joeroe** [comment]
It's there now :)
