### ISSUE TITLE
List layout is broken: Empty line after first level

### ISSUE THREAD

**Issue by nevrome** [sslarch/sslarch.github.io#42]
Do you know where this might be coming from @joeroe?

![image](https://user-images.githubusercontent.com/10789038/121253600-992fb180-c8a9-11eb-93cb-180e7bed03b9.png)

**Comment by joeroe** [comment]
The lines between the first level elements in the source caused an extra `<p>` tag to be inserted around the text of the first level... which I didn't expect. I will see if I can think of a CSS fix but it doesn't make much sense to me. I noticed GitHub's rendering of lists from markdown is similar.

For now removing the lines got rid of it.

**Comment by nevrome** [comment]
Alright - thanks for the fast fix!
